language: perl
perl:
  - "5.10.1-thr"
  - "5.12.0-thr"
  - "5.14.4-thr"
  - "5.18.3-thr"
  - "5.20.1-thr"
  - "5.22.0-thr"
cache:
  directories:
    - $HOME/samtools-$SAMTOOLSVERSION
sudo:
  false
addons:
  apt:
    packages:
    - ncbi-blast+
env:
    - SAMTOOLSVERSION="1.3"
    - SAMTOOLSVERSION="1.2"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm --quiet --notest File::Which Log::Log4perl
install:
    - export PROOVREADDIR=$PWD && make && export PATH=$PWD/bin:"$PATH"
    - cd $HOME && wget 'https://github.com/samtools/samtools/releases/download/'"$SAMTOOLSVERSION"'/samtools-'"$SAMTOOLSVERSION"'.tar.bz2'
    - tar xjf samtools-"$SAMTOOLSVERSION".tar.bz2
    - cd samtools-"$SAMTOOLSVERSION" && make && export PATH=$PWD:"$PATH" && ls && pwd && cd -
    - mkdir -p /tmp/shunit2 && cd /tmp/shunit2 && wget 'https://github.com/greatfireball/shunit2/archive/v2.1.7.tar.gz' -O - | tar xzf - --strip 1
script: 
    - cd $PROOVREADDIR/test && bash testInstallation.sh && bash testSeqFilterError.sh
notifications:
    slack:
        secure: Mu7v0562KyuYMc76eg+9UWtqdF25fH9+ZKBzDD19h41YkjzxCmdPvF+jyD0SJGTsMZh0lKXSt8Ftqb9EWk3JDqzrkNOsDQunNuFwOgT/kF9i0s69mYl7KYR8vUUFHZirJ2aEXrWkeM1kF/tcopmMp/YytALKDDSoW1/6jHRj/go=
